language: cpp
sudo: false
services: docker
dist: trusty

matrix:
    include:
        - compiler: clang
          env: BUILD_TYPE=Release
        - compiler: g++
          env: BUILD_TYPE=Release
        - compiler: g++
          env: BUILD_TYPE=Debug COVERAGE=--coverage
        - compiler: clang
          env: BUILD_TYPE=Release WERROR=-Werror
        - compiler: g++
          env: BUILD_TYPE=Release WERROR=-Werror
    allow_failures:
        - env: BUILD_TYPE=Release WERROR=-Werror

before_install:
    - travis_retry timeout 120 docker pull nuto/nuto_docker:dev
    - docker run -itd --name dock -u 0 -v $(pwd):/home/nuto/source nuto/nuto_docker:dev

script:
    - docker exec dock cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="$COVERAGE $WERROR" ../source
    - docker exec dock make -j2
    - docker exec dock ctest
    - if [[ "$COVERAGE" == "--coverage" ]]; then docker exec dock lcov --directory . --capture --output-file ../source/coverage.info; fi
    - if [[ "$COVERAGE" == "--coverage" ]]; then docker exec dock lcov --remove ../source/coverage.info 'usr/*' --output-file ../source/coverage.info; fi
    - if [[ "$COVERAGE" == "--coverage" ]]; then docker exec dock lcov --remove ../source/coverage.info '*/tests/*' --output-file ../source/coverage.info; fi
    - if [[ "$COVERAGE" == "--coverage" ]]; then bash <(curl -s https://codecov.io/bash); fi
    #- docker exec dock bash ../source/scripts/check_install.sh
